### ISSUE TITLE
Android 6MB AsyncStorage limit causing disasters for users (move large data out of AsyncStorage and into app storage directory)

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-rn#1611]

**Comment by mitchdowney** [comment]
It appears this is happening on Android when a user is subscribed to custom RSS feeds that exceed the 6MB AsyncStorage limit:

> Error: database or disk is full (code 13 SQLITE_FULL)
>     at convertError (AsyncStorage.native.js:408:15)
>     at AsyncStorage.native.js:401:57
>     at Array.map (<anonymous>)
>     at convertErrors (AsyncStorage.native.js:401:48)
>     at AsyncStorage.native.js:122:22
>     at MessageQueue.__invokeCallback (MessageQueue.js:465:13)
>     at MessageQueue.js:127:12
>     at MessageQueue.__guard (MessageQueue.js:370:9)
>     at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126:10)
>     at debuggerWorker.js:69:58

**Comment by mitchdowney** [comment]
This line appears to be the trouble-maker: https://github.com/podverse/podverse-rn/blob/5dbd022d09a454868ffd668dea0bcd7e8d30ffbf/src/services/parser.ts#L158

**Comment by mitchdowney** [comment]
Updated the title of this issue since reaching the 6MB limit on Android can cause all kinds of disasters for users.

**Comment by mitchdowney** [comment]
This should be fixed in v4.12.3
