### ISSUE TITLE
crash on launch on android

### ISSUE THREAD

**Issue by kctipton** [podverse/podverse-rn#2177]
**Describe the bug**
Press on the icon, it tries to launch, immediately closes back down.  This started in April.  My version was downloaded from Google Play, but someone in Discord says they have same problem from an F-Droid version.

**To Reproduce**
1. Launch in the typical way, by tapping the icon.

**Expected behavior**
It used to launch just fine til sometime in April.

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: Galaxy Tab A (2017)
 - OS: [Android version 9]
 - App Version [Podverse 4.16.3]

**Additional context**

I grabbed crash info through 'adb logcat' after getting advice from someone who knows what's what.
Here are 3 crashes on launch, in succession:

05-29 19:02:34.392  8009  8055 E AndroidRuntime: FATAL EXCEPTION: create_react_context
05-29 19:02:34.392  8009  8055 E AndroidRuntime: Process: com.podverse, PID: 8009
05-29 19:02:34.392  8009  8055 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/base.apk", zip file "/data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.armeabi_v7a.apk", zip file "/data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.en.apk", zip file "/data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.es.apk", zip file "/data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.tvdpi.apk"],nativeLibraryDirectories=[/data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/lib/arm, /data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/base.apk!/lib/armeabi-v7a, /data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a, /data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.en.apk!/lib/armeabi-v7a, /data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.es.apk!/lib/armeabi-v7a, /data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.tvdpi.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]] couldn't find "libmmkv.so"
05-29 19:02:34.392  8009  8055 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
05-29 19:02:34.392  8009  8055 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1669)
05-29 19:02:34.392  8009  8055 E AndroidRuntime: 	at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:226)
05-29 19:02:34.392  8009  8055 E AndroidRuntime: 	at com.tencent.mmkv.MMKV.initialize(MMKV.java:208)
05-29 19:02:34.392  8009  8055 E AndroidRuntime: 	at com.tencent.mmkv.MMKV.initialize(MMKV.java:94)
05-29 19:02:34.392  8009  8055 E AndroidRuntime: 	at com.eko.RNBackgroundDownloaderModule.<init>(RNBackgroundDownloaderModule.java:175)
05-29 19:02:34.392  8009  8055 E AndroidRuntime: 	at com.eko.RNBackgroundDownloaderPackage.createNativeModules(RNBackgroundDownloaderPackage.java:15)
05-29 19:02:34.392  8009  8055 E AndroidRuntime: 	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
05-29 19:02:34.392  8009  8055 E AndroidRuntime: 	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
05-29 19:02:34.392  8009  8055 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1425)
05-29 19:02:34.392  8009  8055 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1396)
05-29 19:02:34.392  8009  8055 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1287)
05-29 19:02:34.392  8009  8055 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:136)
05-29 19:02:34.392  8009  8055 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1065)
05-29 19:02:34.392  8009  8055 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)

05-29 19:02:47.855  8238  8327 E AndroidRuntime: FATAL EXCEPTION: create_react_context
05-29 19:02:47.855  8238  8327 E AndroidRuntime: Process: com.podverse, PID: 8238
05-29 19:02:47.855  8238  8327 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/base.apk", zip file "/data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.armeabi_v7a.apk", zip file "/data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.en.apk", zip file "/data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.es.apk", zip file "/data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.tvdpi.apk"],nativeLibraryDirectories=[/data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/lib/arm, /data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/base.apk!/lib/armeabi-v7a, /data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a, /data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.en.apk!/lib/armeabi-v7a, /data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.es.apk!/lib/armeabi-v7a, /data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.tvdpi.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]] couldn't find "libmmkv.so"
05-29 19:02:47.855  8238  8327 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
05-29 19:02:47.855  8238  8327 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1669)
05-29 19:02:47.855  8238  8327 E AndroidRuntime: 	at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:226)
05-29 19:02:47.855  8238  8327 E AndroidRuntime: 	at com.tencent.mmkv.MMKV.initialize(MMKV.java:208)
05-29 19:02:47.855  8238  8327 E AndroidRuntime: 	at com.tencent.mmkv.MMKV.initialize(MMKV.java:94)
05-29 19:02:47.855  8238  8327 E AndroidRuntime: 	at com.eko.RNBackgroundDownloaderModule.<init>(RNBackgroundDownloaderModule.java:175)
05-29 19:02:47.855  8238  8327 E AndroidRuntime: 	at com.eko.RNBackgroundDownloaderPackage.createNativeModules(RNBackgroundDownloaderPackage.java:15)
05-29 19:02:47.855  8238  8327 E AndroidRuntime: 	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
05-29 19:02:47.855  8238  8327 E AndroidRuntime: 	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
05-29 19:02:47.855  8238  8327 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1425)
05-29 19:02:47.855  8238  8327 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1396)
05-29 19:02:47.855  8238  8327 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1287)
05-29 19:02:47.855  8238  8327 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:136)
05-29 19:02:47.855  8238  8327 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1065)
05-29 19:02:47.855  8238  8327 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)

05-29 19:04:01.295  8618  8647 E AndroidRuntime: FATAL EXCEPTION: create_react_context
05-29 19:04:01.295  8618  8647 E AndroidRuntime: Process: com.podverse, PID: 8618
05-29 19:04:01.295  8618  8647 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/base.apk", zip file "/data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.armeabi_v7a.apk", zip file "/data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.en.apk", zip file "/data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.es.apk", zip file "/data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.tvdpi.apk"],nativeLibraryDirectories=[/data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/lib/arm, /data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/base.apk!/lib/armeabi-v7a, /data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a, /data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.en.apk!/lib/armeabi-v7a, /data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.es.apk!/lib/armeabi-v7a, /data/app/com.podverse-nZ2tFynsq8TXW8XolYHK8g==/split_config.tvdpi.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]] couldn't find "libmmkv.so"
05-29 19:04:01.295  8618  8647 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
05-29 19:04:01.295  8618  8647 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1669)
05-29 19:04:01.295  8618  8647 E AndroidRuntime: 	at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:226)
05-29 19:04:01.295  8618  8647 E AndroidRuntime: 	at com.tencent.mmkv.MMKV.initialize(MMKV.java:208)
05-29 19:04:01.295  8618  8647 E AndroidRuntime: 	at com.tencent.mmkv.MMKV.initialize(MMKV.java:94)
05-29 19:04:01.295  8618  8647 E AndroidRuntime: 	at com.eko.RNBackgroundDownloaderModule.<init>(RNBackgroundDownloaderModule.java:175)
05-29 19:04:01.295  8618  8647 E AndroidRuntime: 	at com.eko.RNBackgroundDownloaderPackage.createNativeModules(RNBackgroundDownloaderPackage.java:15)
05-29 19:04:01.295  8618  8647 E AndroidRuntime: 	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
05-29 19:04:01.295  8618  8647 E AndroidRuntime: 	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
05-29 19:04:01.295  8618  8647 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1425)
05-29 19:04:01.295  8618  8647 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1396)
05-29 19:04:01.295  8618  8647 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1287)
05-29 19:04:01.295  8618  8647 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:136)
05-29 19:04:01.295  8618  8647 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1065)
05-29 19:04:01.295  8618  8647 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)

**Comment by lovegaoshi** [comment]
this originates from switching to a background downloader that uses mmkv
https://github.com/podverse/podverse-rn/commit/494e445da865def90c64ba4b78095029246f7289
related:
https://github.com/Tencent/MMKV/issues/343

**Comment by mitchdowney** [comment]
We are archiving all Github issues and PRs that pertain to the previous generation Podverse. The Podverse dev team is currently 100% focused on the next generation app, and will be only working on next gen Github issues going forward.

If you would like to see a work-in-progress demo of the upcoming Podverse website, please visit https://alpha.podverse.fm. Our tentative release date is Spring 2026.

If you're a developer who may be interested in contributing to Podverse Next-Gen, please see our [Local Dev Setup documentation](https://github.com/podverse/podverse-ops/blob/v5-develop/dev/local-dev-setup.md). We can also be reached through [Matrix or Discord](https://podverse.fm/contact).

I'm sorry for the abrupt announcement, but thank you for your bug reports and feature requests.
